export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  TIMELOG_OVERLAP: "TIMELOG_OVERLAP",
  TIMER_ALREADY_ACTIVE: "TIMER_ALREADY_ACTIVE",
  TIMER_NOT_ACTIVE: "TIMER_NOT_ACTIVE",
  TIMER_ALREADY_PAUSED: "TIMER_ALREADY_PAUSED",
  TIMER_NOT_PAUSED: "TIMER_NOT_PAUSED",
  TIMER_AUTOSTOPPED: "TIMER_AUTOSTOPPED",
  TIMELOG_NOT_EDITABLE: "TIMELOG_NOT_EDITABLE",
  TIMESHEET_CASCADE_REQUIRED: "TIMESHEET_CASCADE_REQUIRED",
  TIMESHEET_BLOCKED_BY_REJECTED: "TIMESHEET_BLOCKED_BY_REJECTED",
  TIMESHEET_AMENDMENT_PENDING: "TIMESHEET_AMENDMENT_PENDING",
  TIMESHEET_INVALID_STATUS: "TIMESHEET_INVALID_STATUS",
  CONFLICT: "CONFLICT",
  WORKSPACE_REQUIRED: "WORKSPACE_REQUIRED",
  EMAIL_EXISTS: "EMAIL_EXISTS",
  EMAIL_ALREADY_REGISTERED: "EMAIL_ALREADY_REGISTERED",
  ALREADY_IN_ORGANIZATION: "ALREADY_IN_ORGANIZATION",
  MEMBER_ALREADY_EXISTS: "MEMBER_ALREADY_EXISTS",
  SELF_REGISTRATION_DISABLED: "SELF_REGISTRATION_DISABLED",
  SIGNUP_DISABLED: "SIGNUP_DISABLED",
  COMMERCIAL_FEATURES_DISABLED: "COMMERCIAL_FEATURES_DISABLED",
  NOTIFICATION_NOT_FOUND: "NOTIFICATION_NOT_FOUND",
  PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
  PAYMENT_REQUIRED: "PAYMENT_REQUIRED",
  EXPORT_NOT_READY: "EXPORT_NOT_READY",
  TENANT_DELETE_PRECONDITION_FAILED: "TENANT_DELETE_PRECONDITION_FAILED",
  EXPORT_WAIVED_REQUIRED: "EXPORT_WAIVED_REQUIRED",
  ENTITY_INACTIVE: "ENTITY_INACTIVE"
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export interface ApiErrorBody {
  code: ErrorCode;
  message: string;
  details?: unknown;
}
